/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/f40mKzIiBBO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import React from 'react';
import Link from "next/link"
import { CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Image from 'next/image'

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col bg-gray-100 dark:bg-gray-950">
      <header className="bg-white shadow dark:bg-gray-900">
        <div className="container mx-auto flex h-16 max-w-6xl items-center justify-between px-4 md:px-6">
          <Link className="flex items-center gap-2 text-lg font-bold" href="#">
            <GiftIcon className="h-6 w-6 text-gray-900 dark:text-gray-50" />
            Rewards Program
          </Link>
          <div className="flex items-center gap-4">
            <Link className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="api/select_account">
              Sign In
            </Link>
            <Link
              className="rounded-md bg-gray-900 px-4 py-2 text-white hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 dark:bg-primary-500 dark:hover:bg-slate-700 dark:bg-slate-800"
              href="api/select_account"
            >
              Sign Up
            </Link>
          </div>
        </div>
      </header>
      <main className="flex-1 bg-gray-100 dark:bg-gray-950">
        <section className="container mx-auto max-w-6xl px-4 py-12 md:px-6 md:py-16">
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
            <div>
              <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50 sm:text-4xl">
                Earn and Redeem Rewards
              </h1>
              <p className="mt-4 text-lg text-gray-500 dark:text-gray-400">
                Participate in our rewards program to earn points and redeem them for gift cards and vouchers.
              </p>
              <div className="mt-8">
                <Link
                  className="rounded-md bg-gray-900 px-4 py-2 text-white hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 dark:bg-primary-500 dark:hover:bg-slate-800 dark:bg-slate-900"
                  href="/rewards"
                >
                  Join Now
                </Link>
              </div>
            </div>
            <div>
              <Image
                alt="Rewards Illustration"
                className="mx-auto"
                height={500}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "500/500",
                  objectFit: "cover",
                }}
                width={500}
              />
            </div>
          </div>
        </section>
        <section className="bg-white py-12 dark:bg-gray-900">
          <div className="container mx-auto max-w-6xl px-4 md:px-6">
            <h2 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-gray-50 sm:text-3xl">
              How it Works
            </h2>
            <div className="mt-8 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
              <div className="rounded-md bg-gray-100 p-6 shadow dark:bg-gray-800">
                <WalletIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
                <h3 className="mt-4 text-xl font-bold">Earn Points</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  Participate in various activities to earn reward points.
                </p>
              </div>
              <div className="rounded-md bg-gray-100 p-6 shadow dark:bg-gray-800">
                <GiftIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
                <h3 className="mt-4 text-xl font-bold">Redeem Rewards</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  Use your earned points to redeem gift cards and vouchers.
                </p>
              </div>
              <div className="rounded-md bg-gray-100 p-6 shadow dark:bg-gray-800">
                <TrophyIcon className="h-8 w-8 text-gray-900 dark:text-gray-50" />
                <h3 className="mt-4 text-xl font-bold">Earn Badges</h3>
                <p className="mt-2 text-gray-500 dark:text-gray-400">
                  Complete challenges and earn badges to unlock exclusive rewards.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-12 dark:bg-gray-950">
          <div className="container mx-auto max-w-6xl px-4 md:px-6">
            <h2 className="text-2xl font-bold tracking-tight text-gray-900 dark:text-gray-50 sm:text-3xl">
              Rewards Catalog
            </h2>
            <div className="mt-8 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <h3 className="text-xl font-bold">$25 Amazon Gift Card</h3>
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">5,000 pts</div>
                  </div>
                  <p className="mt-2 text-gray-500 dark:text-gray-400">
                    Redeem your points for a $25 Amazon gift card.
                  </p>
                </CardContent>
                <CardFooter>
                  <Button className="w-full">Redeem</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <h3 className="text-xl font-bold">$50 Visa Gift Card</h3>
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">10,000 pts</div>
                  </div>
                  <p className="mt-2 text-gray-500 dark:text-gray-400">Redeem your points for a $50 Visa gift card.</p>
                </CardContent>
                <CardFooter>
                  <Button className="w-full">Redeem</Button>
                </CardFooter>
              </Card>
              <Card>
                <CardContent>
                  <div className="flex items-center justify-between">
                    <h3 className="text-xl font-bold">$100 Walmart Voucher</h3>
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">20,000 pts</div>
                  </div>
                  <p className="mt-2 text-gray-500 dark:text-gray-400">
                    Redeem your points for a $100 Walmart voucher.
                  </p>
                </CardContent>
                <CardFooter>
                  <Button className="w-full">Redeem</Button>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-white py-6 shadow dark:bg-gray-900">
        <div className="container mx-auto max-w-6xl px-4 md:px-6">
          <div className="flex items-center justify-between">
            <p className="text-gray-500 dark:text-gray-400">© 2023 Rewards Program. All rights reserved.</p>
            <div className="flex items-center gap-4">
              <Link className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="#">
                Privacy Policy
              </Link>
              <Link className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50" href="#">
                Terms of Service
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

function GiftIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="3" y="8" width="18" height="4" rx="1" />
      <path d="M12 8v13" />
      <path d="M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7" />
      <path d="M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5" />
    </svg>
  )
}


function TrophyIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>
  )
}


function WalletIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 7V4a1 1 0 0 0-1-1H5a2 2 0 0 0 0 4h15a1 1 0 0 1 1 1v4h-3a2 2 0 0 0 0 4h3a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1" />
      <path d="M3 5v14a2 2 0 0 0 2 2h15a1 1 0 0 0 1-1v-4" />
    </svg>
  )
}
