/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/z7j8V217pkB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export default function SelectAccount() {
  return (
    <div className="flex h-screen w-full items-center justify-center bg-gray-100 dark:bg-gray-900">
      <div className="mx-4 w-full max-w-md space-y-6 rounded-lg bg-white p-6 shadow-lg dark:bg-gray-800 sm:p-8">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-100">Selecciona tu cuenta</h1>
          <p className="text-gray-500 dark:text-gray-400">
            Elige si tienes una cuenta de negocio o una cuenta de cliente.
          </p>
        </div>
        <div className="grid gap-4">
          <Link
            className="inline-flex h-12 w-full items-center justify-center rounded-md bg-gray-900 px-6 text-base font-medium text-white transition-colors hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:bg-gray-500 dark:hover:bg-gray-400 dark:focus:ring-gray-400 dark:focus:ring-offset-gray-800"
            href="auth/business/login"
          >
            Cuenta Business
          </Link>
          <Link
            className="inline-flex h-12 w-full items-center justify-center rounded-md border border-gray-300 bg-white px-6 text-base font-medium text-gray-900 transition-colors hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100 dark:hover:bg-gray-700 dark:focus:ring-gray-400 dark:focus:ring-offset-gray-800 dark:border-gray-800"
            href="auth/customer/login"
          >
            Cuenta Cliente
          </Link>
        </div>
      </div>
    </div>
  )
}
